#from ubuntu:wily
FROM ansible/ubuntu14.04-ansible

RUN 	apt-get -y update \
    && apt-get -y install dialog python-keystoneclient python-dialog \
    python-heatclient python-novaclient python-glanceclient \
    && apt-get -y clean all 

COPY FILES.deploy-heat /

VOLUME /nds/config

#
## Ansible setup for coreos
#
RUN ansible-galaxy install defunctzombie.coreos-bootstrap 
#CMD deploy - leave as bash for now

