from ubuntu:wily

RUN 	apt-get -y update \
    && apt-get -y install dialog python-dialog python-heatclient python-novaclient \
    && apt-get -y clean all 

#RUN apt-get -y install python-pip && pip install pythondialog python-novaclient python-heatclient 

COPY FILES.deploy-heat /

RUN mkdir -p /nds/config/

WORKDIR /usr/local/bin
CMD deploy

