from ubuntu:wily

RUN 	apt-get -y update \
    && apt-get -y install dialog python-keystoneclient python-dialog \
    python-heatclient python-novaclient python-glanceclient \
    && apt-get -y clean all 

COPY FILES.deploy-heat /

VOLUME /nds/config

#ENV OS_REGION_NAME ''
#ENV OS_TENANT_ID ''
#ENV OS_PROJECT_NAME ''
#ENV OS_PASSWORD ''
#ENV OS_AUTH_URL ''
#ENV OS_USERNAME ''
#ENV OS_TENANT_NAME ''

WORKDIR /usr/local/bin
CMD deploy

