apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-etcd
  labels:
    component: ndslabs-etcd
spec:
  replicas: 1
  selector:
    component: ndslabs-etcd
  template:
    metadata:
      labels:
        component: ndslabs-etcd
    spec:
      containers:
      - image: ndslabs/etcd:2.2.5 
        command:
        - /usr/local/bin/etcd
        - --bind-addr=0.0.0.0:4001
        - --advertise-client-urls=http://127.0.0.1:4001
        - --data-dir=/var/etcd/data
        name: ndslabs-etcd
        ports:
        - containerPort: 4001
          name: server
          protocol: TCP
        volumeMounts: 
        - name: varetcd
          mountPath: /var/etcd
      restartPolicy: Always
      volumes:
       - hostPath:
            path: "/ndslabs/data/etcd"
         name: varetcd
