apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ndslabs-auth
  annotations:
    "nginx.ingress.kubernetes.io/auth-url": "https://www.{{ DOMAIN }}/cauth/auth"
    "nginx.ingress.kubernetes.io/auth-signin": "https://www.{{ DOMAIN }}/login/#/"
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
spec:
  tls:
  - hosts:
    - www.{{ DOMAIN }}
    secretName: ndslabs-tls-secret
  rules:
  - host: www.{{ DOMAIN }}
    http:
      paths:
      - path: /logs
        backend:
          serviceName: ndslabs-webui
          servicePort: 80
      - path: /dashboard
        backend:
          serviceName: ndslabs-webui
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ndslabs-open
  annotations:
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
spec:
  tls:
  - hosts:
    - www.{{ DOMAIN }}
    secretName: ndslabs-tls-secret
  rules:
  - host: www.{{ DOMAIN }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: ndslabs-apiserver
          servicePort: 30001
      - path: /
        backend:
          serviceName: ndslabs-webui
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  labels:
    app: default-http-backend
spec:
  selector:
    app: default-http-backend
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: default-http-backend
spec:
  replicas: 1
  selector:
    app: default-http-backend
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        # Any image is permissable as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: ndslabs/ndslabs-default-backend:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 256Mi
---
apiVersion: v1
data:
  server-name-hash-bucket-size: "512"
  ssl-protocols: "TLSv1.2"
  proxy-read-timeout: "300"
  proxy-send-timeout: "300"
  custom-http-errors: "404,502,503"
  body-size: 50m
kind: ConfigMap
metadata:
  name: nginx-ingress-conf
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ilb-rc
  labels:
    app: nginx-ilb
spec:
  replicas: 1
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=default/default-http-backend
        - --healthz-port=10254
        - --configmap=$(POD_NAMESPACE)/nginx-ingress-conf
        - --default-ssl-certificate=$(POD_NAMESPACE)/ndslabs-tls-secret
      hostNetwork: true
      
