apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-webui
spec:
  replicas: 1
  selector:
    component: ndslabs-webui
  template:
    metadata:
      labels:
        component: ndslabs-webui
    spec:
      containers:
      - name: ndslabs-webui
        image: ndslabs/angular-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: DOMAIN
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.domain
          - name: APISERVER_SECURE
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: tls.enable
          - name: ANALYTICS_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.analytics_tracking_id
          - name: SUPPORT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.support_email
          - name: GIT_DROPIN_REPO
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: git.dropin_repo
          - name: GIT_DROPIN_BRANCH
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: git.dropin_branch
          - name: APISERVER_HOST
            value: "www.$(DOMAIN)"
          - name: APISERVER_PORT
            value: ""
          - name: APISERVER_PATH
            value: "/api"
        readinessProbe:
          httpGet:
            path: /asset/png/favicon-2-32x32.png
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 120
