apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-smtp
  labels:
    component: ndslabs-smtp
spec:
  replicas: 1
  selector:
    component: ndslabs-smtp
  template:
    metadata:
      labels:
        component: ndslabs-smtp
    spec:
      containers:
      - image: namshi/smtp
        name: ndslabs-smtp
        ports:
        - containerPort: 25
          name: server
          protocol: TCP
        env:
          - name: MAILNAME
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.host
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.port
          - name: GMAIL_USER
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.gmail_user
          - name: GMAIL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.gmail_pass
          - name: SES_USER
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.aws_ses_user
          - name: SES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.aws_ses_password
          - name: SMARTHOST_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_address
          - name: SMARTHOST_PORT
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_port
          - name: SMARTHOST_USER
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_user
          - name: SMARTHOST_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_password
      restartPolicy: Always
