
# Run after glfs server and glfs clients are deployed 

- name: Create Backup key file
  copy: dest=/tmp/backup-key.pem src=/root/SAVED_AND_SENSITIVE_VOLUME/{{ backup_key }}

- name: Secret status - backup-key
  shell: /opt/bin/kubectl get secret backup-key
  register: backupsecret
  failed_when: backupsecret.rc < 0

- name: Cluster backup create config secrets
  shell: /opt/bin/kubectl create secret generic backup-key --from-file=ssh-privatekey=/tmp/backup-key.pem
  when: backupsecret.rc != 0

- name: Cluster backup | copy spec
  template: src={{ item }}.j2 dest=/tmp/{{ item }}
  with_items:
    - backup.job.yaml
    - backup.shell.yaml

# CronJobs currently throws an error on "kubectl apply" (supposedly fixed in 1.6+)
# See https://github.com/kubernetes/kubernetes/issues/39872
- name: Cluster backup | deploy CronJob
  shell: "/opt/bin/kubectl create -f /tmp/backup.job.yaml || /opt/bin/kubectl replace -f /tmp/backup.job.yaml"
