
- name: Cluster Addons| populate template
  template: src="{{ item }}.j2" dest="/tmp/{{ item }}"
  with_items:
    - kube-system-ingress.yaml


################################
#  Create Ingress Rules: kube-lma-ingress
################################
- name: Cluster Addon init | create kube-lma-ingress rules
  command: /opt/bin/kubectl apply --namespace=kube-system -f "/tmp/kube-system-ingress.yaml"


################################
#  Create SkyDNS Service / Controller
################################
- name: Cluster DNS | create DNS stack - kube-system
  command: /opt/bin/kubectl apply -f /etc/kubernetes/addons/dns/
  when: dns_setup


################################
#  Create Grafana Service / Controller
################################
- name: Cluster LMA - Grafana | create grafana stack - kube-system
  command: /opt/bin/kubectl apply -f /etc/kubernetes/addons/cluster-monitoring/
  when: cluster_monitoring


################################
#  Create Kibana Service / Controller
################################
- name: Cluster LMA - Kibana | create ELK stack - kube-system
  command: /opt/bin/kubectl apply -f /etc/kubernetes/addons/cluster-logging/
  when: cluster_logging


################################
#  Create Kube UI Service / Controller
################################
- name: Cluster LMA - Kube UI | create kube-ui stack - kube-system
  command: /opt/bin/kubectl apply -f /etc/kubernetes/addons/kube-ui/
  when: kube_ui


################################
#  Create Kube Dashboard Service / Controller
################################
- name: Cluster LMA - Kubernetes Dashboard | create kube-dash stack - kube-system
  command: /opt/bin/kubectl apply -f /etc/kubernetes/addons/kube-dash/
  when: kube_dash

