---

flavor_small: m1.large              # 20G disk, 8G ram, 2cpu
flavor_medium: m1.large             # 20G disk, 8G ram, 2cpu
flavor_large: m1.2xlarge            # 20G disk, 32Gram, 8cpu

native_dns: sdsc.edu

ndslabs_domain: "{{ logical_cluster_name }}.ndslabs.org" 
 
smtp_host: outbound.ucsd.edu
smtp_tls: false
